### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NatalectEntertainment** [Delta2Force/MCVmComputers#157]
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/23/21 2:32 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcvmcomputers.client.gui.GuiPCEditing.method_25394(GuiPCEditing.java:475)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcvmcomputers.client.gui.GuiPCEditing.method_25394(GuiPCEditing.java:475)

-- Screen render details --
Details:
	Screen name: mcvmcomputers.client.gui.GuiPCEditing
	Mouse location: Scaled: (255, 122). Absolute: (511.352539, 244.237000)
	Screen size: Scaled: (427, 240). Absolute: (1708, 960). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['JeriahNealLive'/1042, l='ClientLevel', x=252.33, y=64.00, z=86.70]]
	Chunk stats: Client Chunk Cache: 169, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,64,64), Chunk: (at 0,4,0 in 14,4; contains blocks 224,0,64 to 239,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1053 game time, 1053 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1064049088 bytes (1014 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.20.2+build.402-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad95
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd195
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd695
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea18895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa195
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced895
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced895
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de695
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e95
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049095
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea18895
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e95
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e95
		fabricloader: Fabric Loader 0.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		mcvmcomputers: VM Computers 1.4.13
		minecraft: Minecraft 1.16.3
	Launched Version: fabric-loader-0.11.1-1.16.3
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon Pro 560X OpenGL Engine GL version 2.1 ATI-4.2.13, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla, file/RTX
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

**Comment by NatalectEntertainment** [comment]
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
Exit Code: 255
