### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tmddn3070** [Delta2Force/MCVmComputers#217]
I was using the mod once, and the moment I right-click on the monitor or keyboard, the game crash with that log. how do i solve this?

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: java.nio.DoubleBuffer.clear()Ljava/nio/DoubleBuffer;
Exit Code: -1

console log:
Reported exception thrown!
net.minecraft.class_148: Rendering screen
at net.minecraft.class_757.method_3192(class_757.java:625)
at net.minecraft.class_310.method_1523(class_310.java:1048)
at net.minecraft.class_310.method_1514(class_310.java:681)
at net.minecraft.client.main.Main.main(Main.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoSuchMethodError: java.nio.DoubleBuffer.clear()Ljava/nio/DoubleBuffer;
at mcvmcomputers.client.gui.GuiFocus.method_25394(GuiFocus.java:78)
at net.minecraft.class_757.method_3192(class_757.java:616)
... 10 more

**Comment by Delta2Force** [comment]
This is a Java issue, please try running the mod using Java 8 for now. When the mod version for 1.17 comes out, this bug will no longer be a problem.

**Comment by tmddn3070** [comment]
thanks!

**Comment by y2k04** [comment]
Duplicate of #184
