### ISSUE TITLE
fabric not having any of the latest mod's stuff

### ISSUE THREAD

**Issue by zeyno-pixel** [Delta2Force/MCVmComputers#238]
error:

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'VM Computers' (mcvmcomputers) 1.4.15 (C:\Users\rolle\AppData\Roaming\.minecraft\mods\mcvmcomputers-1.4.15.jar) with any version that is compatible with:
		 - minecraft 1.15.2
Unmet dependency listing:
	 - Mod 'VM Computers' (mcvmcomputers) 1.4.15 requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.15.2!
		 - 'Minecraft' (minecraft) 1.15.2 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'VM Computers' (mcvmcomputers) 1.4.15, reason: to replace
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'VM Computers' (mcvmcomputers) 1.4.15 (C:\Users\rolle\AppData\Roaming\.minecraft\mods\mcvmcomputers-1.4.15.jar) with any version that is compatible with:
		 - minecraft 1.15.2
Unmet dependency listing:
	 - Mod 'VM Computers' (mcvmcomputers) 1.4.15 requires version 1.16.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.15.2!
		 - 'Minecraft' (minecraft) 1.15.2 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'VM Computers' (mcvmcomputers) 1.4.15, reason: to replace
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more

**Comment by Delta2Force** [comment]
Try running the mod using Minecraft 1.16.5.
