### ISSUE TITLE
Fabric not detected by VM Computers, using Fabric 0.12.11 on MultiMC

### ISSUE THREAD

**Issue by ioletsgo** [Delta2Force/MCVmComputers#239]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'VM Computers' (mcvmcomputers) 1.4.15 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'VM Computers' (mcvmcomputers) 1.4.15 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 11 more

**Comment by y2k04** [comment]
Have you tried downloading the fabric api mod?

**Comment by Maks7594** [comment]
> Have you tried downloading the fabric api mod?

Doesn't say anything about fabric api, only fabric.

**Comment by y2k04** [comment]
Fabric API is required for the mod to work. That error is because you don't have the Fabric API mod installed. You can get it from https://modrinth.com/mod/fabric-api
