### ISSUE TITLE
VM does not start, also brings performance down to unplayable speeds (6.1.50)

### ISSUE THREAD

**Issue by enderman0125** [Delta2Force/MCVmComputers#304]
This mod is kind of a hit or miss when it comes to well, functioning. The VM "starts", but does not show up on screen, and it shows up as "Aborted" or "Powered Off" in the VirtualBox UI, while also grinding the game's framerate down to single digits until the VM is stopped.
![image](https://github.com/Delta2Force/MCVmComputers/assets/104173450/b176373f-2598-46bf-a57f-165331ca825b)
![image](https://github.com/Delta2Force/MCVmComputers/assets/104173450/0ac2fdeb-53ae-4944-9e4c-d4e1414041cc)

When turning off the VM ingame, the following message shows up in the console:

```
[20:28:57] [Turn off PC/ERROR]: Uncaught exception in thread "Turn off PC"
org.virtualbox_6_1.VBoxException: VirtualBox error: rc=0x8000ffff The session is not locked (session state: Unlocked) (0x8000ffff)
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10) ~[?:?]
    at org.virtualbox_6_1.ISession.getConsole(ISession.java:214) ~[mcvmcomputers-1.4.15.jar:?]
    at mcvmcomputers.client.gui.GuiPCEditing$1.run(GuiPCEditing.java:550) ~[mcvmcomputers-1.4.15.jar:?]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
Caused by: org.virtualbox_6_1.jaxws.RuntimeFaultMsg: VirtualBox error: rc=0x8000ffff The session is not locked (session state: Unlocked) (0x8000ffff)
    at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_412]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77) ~[?:1.8.0_412]
    at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147) ~[?:1.8.0_412]
    at com.sun.proxy.$Proxy102.iSessionGetConsole(Unknown Source) ~[?:?]
    at org.virtualbox_6_1.ISession.getConsole(ISession.java:205) ~[mcvmcomputers-1.4.15.jar:?]
    ... 2 more
```

When turning it on again, this message shows up in chat:
![image](https://github.com/Delta2Force/MCVmComputers/assets/104173450/b0daca73-0982-414d-b070-b597a36f7993)
...it also shows up on subsequent power ons, until I restart the game (where everything above will simply just happen again), see attached video

https://github.com/Delta2Force/MCVmComputers/assets/104173450/3ed4b25c-0402-4777-ba17-97f6a0cbcb73

Trying to forcibly stop the VM through vboxmanage will also not do anything.
![image](https://github.com/Delta2Force/MCVmComputers/assets/104173450/d97ebc4b-02df-48d8-92a5-a650615c07cc)

I have tried several different VirtualBox versions, all of them yield the same result. Said versions are 7.0.18, 6.1.50, 6.1.46 and 6.1.44.

Running Fabric API 0.42.0+1.16. Game log is also attached
[latest.log](https://github.com/user-attachments/files/16113538/latest.log)

**Comment by BeanzOnT0ast** [comment]
try virtualbox 5 m8

**Comment by enderman0125** [comment]
> try virtualbox 5 m8

I'm very sure that will not make a difference.
