### ISSUE TITLE
Server Error:

### ISSUE THREAD

**Issue by Delta2Force** [Delta2Force/MCVmComputers#39]
Server Error:
```
[06:55:00] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Duplicate id value for 7!
at net.minecraft.class_2945.method_12784(class_2945.java:80) ~[intermediary-server.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.method_5693(EntityFlatScreen.java:58) ~[mcvmcomputers-1.4.3.jar:?]
at net.minecraft.class_1297.<init>(class_1297.java:253) ~[intermediary-server.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.<init>(EntityFlatScreen.java:32) ~[mcvmcomputers-1.4.3.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.<init>(EntityFlatScreen.java:41) ~[mcvmcomputers-1.4.3.jar:?]
at mcvmcomputers.item.ItemFlatScreen.method_7836(ItemFlatScreen.java:32) ~[mcvmcomputers-1.4.3.jar:?]
at net.minecraft.class_1799.method_7913(class_1799.java:206) ~[intermediary-server.jar:?]
at net.minecraft.class_3225.method_14256(class_3225.java:278) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_12065(class_3244.java:966) ~[intermediary-server.jar:?]
at net.minecraft.class_2886.method_12550(class_2886.java:31) ~[intermediary-server.jar:?]
at net.minecraft.class_2886.method_11054(class_2886.java:9) ~[intermediary-server.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-server.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:743) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:138) [intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:725) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:719) [intermediary-server.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:703) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

_Originally posted by @BlueJay113 in https://github.com/Delta2Force/MCVmComputers/issues/36#issuecomment-656520268_

**Comment by Delta2Force** [comment]
I currently don't have a clue why this should happen. It is caused by starting to track the owner's UUID in an EntityFlatScreen, I am unable to recreate the issue though.

**Comment by BlueJay113** [comment]
> I currently don't have a clue why this should happen. It is caused by starting to track the owner's UUID in an EntityFlatScreen, I am unable to recreate the issue though.

Lmao okay

**Comment by Binary-2** [comment]
Glad to see you're still working on this though, keep it up!
